### ISSUE TITLE
A opção "twoside" da classe ifscexam não tem efeito. 

### ISSUE THREAD

**Issue by robertoifsc** [emersonmello/modelos-latex#2]
Olá, Emerson.

Obrigado por prover os modelos Latex para o IFSC. São incrivelmente úteis!

Eu normalmente utilizo a impressão "two side" para listas ou provas para economizar folhas do IFSC. Nesses casos, a paginação sempre à direita fica estranha. Dessa forma, tentei utilizar o seguinte:

`\documentclass[12pt,addpoints, twoside]{ifscexam}`

Ao invés de:

`\documentclass[12pt,addpoints]{ifscexam}`

Conforme discutido [aqui](https://www.overleaf.com/learn/latex/Single_sided_and_double_sided_documents).

Entretanto, não houve alteração alguma nas páginas pares. Eu esperava que o rodapé ficasse espelhado horizontalmente. Será que interpretei ou estou fazendo algo errado?

Obrigado,

Roberto

**Comment by emersonmello** [comment]
Olá @robertoifsc , obrigado por apontar este comportamento incorreto.

Já subi a correção no commit  6b54b03ce07943c564c9ec4caedb8d90aaca4431.
